name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install buildozer
        sudo apt update && sudo apt install -y openjdk-11-jdk
    - name: Build APK
      run: buildozer android debug
